version: 2

models:
  - name: listings_staging
    description: cleaned and reformatted version of listings_raw
    columns:
      - name: date
        description: date listing was extracted
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
          - not_null
      - name: price
        description: price of car
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int64
          - not_null
      - name: odometer
        description: odometer reading of car
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int64
          - not_null
      - name: year
        description: year of car model
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int64
          - not_null
      - name: car_model
        description: car model
        tests:
          - not_null
      - name: type
        description: type relating to car_model
        tests:
          - not_null
      - name: suburb
        description: suburb of listing
        tests:
          - not_null
      - name: state
        description: state of listing
        tests:
          - not_null
  - name: locations_staging
    description: location information for each location found in listings_raw
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - suburb
            - state
            - latitude
            - longitude
    columns:
      - name: suburb
        description: date listing was extracted
        tests:
          - not_null
      - name: state
        description: price of car
        tests:
          - not_null
      - name: latitude
        description: odometer reading of car
        tests:
          - not_null
      - name: longitude
        description: year of car model
        tests:
          - not_null


